### ISSUE TITLE
basemap link issue on big sur  python3.7 geos39

### ISSUE THREAD

**Issue by qianwu2** [libgeos/geos#480]
I got this error after call to _geoslib

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 53, in <module>
    import _geoslib
  File "src/_geoslib.pyx", line 13, in init _geoslib
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88
>>> exit()

**Comment by pramsey** [comment]
Not a GEOS problem that I can see.
