### ISSUE TITLE
Segfault in Hausdorff distance with empty geometries

### ISSUE THREAD

**Issue by jorisvandenbossche** [libgeos/geos#569]
From https://github.com/shapely/shapely/issues/753. I reproduced it locally using GEOS 3.10.1.

Using shapely to show it, but it are easy geometries to test elsewhere:

```
>>> from shapely import wkt
>>> a = wkt.loads("POINT (1 1)")
>>> b = wkt.loads("POINT EMPTY")

>>> a.hausdorff_distance(b)
Segmentation fault (core dumped)
```

Output from gdb backtrace:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff6f409d0 in geos::algorithm::distance::DistanceToPoint::computeDistance(geos::geom::Geometry const&, geos::geom::Coordinate const&, geos::algorithm::distance::PointPairDistance&) () from /home/joris/miniconda3/envs/geo-dev/lib/./libgeos.so.3.10.1
(gdb) bt
#0  0x00007ffff6f409d0 in geos::algorithm::distance::DistanceToPoint::computeDistance(geos::geom::Geometry const&, geos::geom::Coordinate const&, geos::algorithm::distance::PointPairDistance&) ()
   from /home/joris/miniconda3/envs/geo-dev/lib/./libgeos.so.3.10.1
#1  0x00007ffff6f3fe4c in geos::algorithm::distance::DiscreteHausdorffDistance::MaxPointDistanceFilter::filter_ro(geos::geom::Coordinate const*) ()
   from /home/joris/miniconda3/envs/geo-dev/lib/./libgeos.so.3.10.1
#2  0x00007ffff6f40036 in geos::algorithm::distance::DiscreteHausdorffDistance::computeOrientedDistance(geos::geom::Geometry const&, geos::geom::Geometry const&, geos::algorithm::distance::PointPairDistance&)
    () from /home/joris/miniconda3/envs/geo-dev/lib/./libgeos.so.3.10.1
#3  0x00007ffff6f4046d in geos::algorithm::distance::DiscreteHausdorffDistance::distance(geos::geom::Geometry const&, geos::geom::Geometry const&) ()
   from /home/joris/miniconda3/envs/geo-dev/lib/./libgeos.so.3.10.1
#4  0x00007ffff70edeef in GEOSHausdorffDistance_r () from /home/joris/miniconda3/envs/geo-dev/lib/libgeos_c.so
#5  0x00007ffff7338a4a in ffi_call_unix64 () from /home/joris/miniconda3/envs/geo-dev/lib/python3.9/lib-dynload/../../libffi.so.8
#6  0x00007ffff7337fea in ffi_call_int () from /home/joris/miniconda3/envs/geo-dev/lib/python3.9/lib-dynload/../../libffi.so.8
#7  0x00007ffff7351dc7 in _call_function_pointer (argtypecount=<optimized out>, argcount=4, resmem=0x7fffffffcd90, restype=<optimized out>, atypes=<optimized out>, avalues=0x7fffffffcd60, 
    pProc=0x7ffff70edec0 <GEOSHausdorffDistance_r>, flags=4353) at /usr/local/src/conda/python-3.9.7/Modules/_ctypes/callproc.c:920
#8  _ctypes_callproc (pProc=<optimized out>, argtuple=<optimized out>, flags=<optimized out>, argtypes=<optimized out>, restype=<_ctypes.PyCSimpleType at remote 0x555555a21c00>, checker=<optimized out>)
    at /usr/local/src/conda/python-3.9.7/Modules/_ctypes/callproc.c:1263
#9  0x00007ffff735234c in PyCFuncPtr_call (self=0x7ffff715df40, inargs=(93824997820144, 93824997836800, 93825001219648, <CArgObject at remote 0x7ffff7385670>), kwds=<optimized out>)
    at /usr/local/src/conda/python-3.9.7/Modules/_ctypes/_ctypes.c:4201
```

**Comment by pramsey** [comment]
Watch out for that NaN return value (better than a crash though).

**Comment by jorisvandenbossche** [comment]
Thanks for the quick fix!

> Watch out for that NaN return value

Yes, based on the discussion in Watch out for that NaN return value, I think that's what we would expect
