### ISSUE TITLE
Segfault with offsetCurve and distance of 0.0 (GEOS main)

### ISSUE THREAD

**Issue by jorisvandenbossche** [libgeos/geos#850]
From investigating https://github.com/shapely/shapely/issues/1788 and trying it out on latest GEOS main.

Using `geosop`, the following segfaults:

```
$ geosop offsetCurve 0.0 -a "LINESTRING (0 0, 1 0, 1 1)"
Segmentation fault (core dumped)
```

The shapely reproducer:

```python
import shapely
line = shapely.LineString([(0,0), (1,0), (1,1), (0,0)])
line.offset_curve(0.0)
```

Backtrace from gdb:

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
geos::geom::CoordinateSequence::size (this=0x0) at /home/joris/scipy/repos/geos/include/geos/geom/CoordinateSequence.h:188
188	        switch(stride()) {
(gdb) bt
#0  geos::geom::CoordinateSequence::size (this=0x0) at /home/joris/scipy/repos/geos/include/geos/geom/CoordinateSequence.h:188
#1  geos::operation::buffer::OffsetCurve::computeSections (this=0x7fffffff8c90, lineGeom=..., dist=0) at /home/joris/scipy/repos/geos/src/operation/buffer/OffsetCurve.cpp:174
#2  0x00007ffff728986b in geos::operation::buffer::OffsetCurve::computeCurve (this=0x7fffffff8c90, lineGeom=..., dist=0) at /home/joris/scipy/repos/geos/src/operation/buffer/OffsetCurve.cpp:158
#3  0x00007ffff72899e3 in operator() (geom=..., __closure=<optimized out>) at /home/joris/scipy/repos/geos/src/operation/buffer/OffsetCurve.cpp:79
#4  std::__invoke_impl<std::unique_ptr<geos::geom::Geometry>, geos::operation::buffer::OffsetCurve::getCurve()::<lambda(const geos::geom::Geometry&)>&, const geos::geom::Geometry&> (__f=...)
    at /home/joris/miniconda3/envs/geos-dev/x86_64-conda-linux-gnu/include/c++/11.3.0/bits/invoke.h:61
#5  std::__invoke_r<std::unique_ptr<geos::geom::Geometry>, geos::operation::buffer::OffsetCurve::getCurve()::<lambda(const geos::geom::Geometry&)>&, const geos::geom::Geometry&> (__fn=...)
    at /home/joris/miniconda3/envs/geos-dev/x86_64-conda-linux-gnu/include/c++/11.3.0/bits/invoke.h:143
#6  std::_Function_handler<std::unique_ptr<geos::geom::Geometry, std::default_delete<geos::geom::Geometry> >(const geos::geom::Geometry&), geos::operation::buffer::OffsetCurve::getCurve()::<lambda(const geos::geom::Geometry&)> >::_M_invoke(const std::_Any_data &, const geos::geom::Geometry &) (__functor=..., __args#0=...)
    at /home/joris/miniconda3/envs/geos-dev/x86_64-conda-linux-gnu/include/c++/11.3.0/bits/std_function.h:291
#7  0x00007ffff7212cff in std::function<std::unique_ptr<geos::geom::Geometry, std::default_delete<geos::geom::Geometry> > (geos::geom::Geometry const&)>::operator()(geos::geom::Geometry const&) const (
    __args#0=..., this=0x7fffffff8b70) at /home/joris/miniconda3/envs/geos-dev/x86_64-conda-linux-gnu/include/c++/11.3.0/bits/std_function.h:590
#8  geos::geom::util::GeometryMapper::flatMap(geos::geom::Geometry const&, std::function<std::unique_ptr<geos::geom::Geometry, std::default_delete<geos::geom::Geometry> > (geos::geom::Geometry const&)>, std::vector<std::unique_ptr<geos::geom::Geometry, std::default_delete<geos::geom::Geometry> >, std::allocator<std::unique_ptr<geos::geom::Geometry, std::default_delete<geos::geom::Geometry> > > >&) (geom=..., op=..., 
    mapped=...) at /home/joris/scipy/repos/geos/src/geom/util/GeometryMapper.cpp:72
#9  0x00007ffff7212ea2 in geos::geom::util::GeometryMapper::flatMap(geos::geom::Geometry const&, int, std::function<std::unique_ptr<geos::geom::Geometry, std::default_delete<geos::geom::Geometry> > (geos::geom::Geometry const&)>) (geom=..., emptyDim=emptyDim@entry=1, op=...) at /home/joris/scipy/repos/geos/src/geom/util/GeometryMapper.cpp:50
#10 0x00007ffff7287d3f in geos::operation::buffer::OffsetCurve::getCurve (this=this@entry=0x7fffffff8c90) at /home/joris/scipy/repos/geos/src/operation/buffer/OffsetCurve.cpp:82
#11 0x00007ffff73bd421 in operator() (__closure=<optimized out>) at /home/joris/scipy/repos/geos/capi/geos_ts_c.cpp:1195
#12 execute<GEOSOffsetCurve_r(GEOSContextHandle_t, const geos::geom::Geometry*, double, int, int, double)::<lambda()> > (f=..., extHandle=0x555555d765c0) at /home/joris/scipy/repos/geos/capi/geos_ts_c.cpp:425
#13 GEOSOffsetCurve_r (extHandle=0x555555d765c0, g1=0x555555942620, width=0, quadsegs=16, joinStyle=1, mitreLimit=5) at /home/joris/scipy/repos/geos/capi/geos_ts_c.cpp:1181
```

Given that this only happens on GEOS main and not 3.11.1, I suppose this is related to the recent changes to make OffsetCurve behave better with self-intersecting lines: https://github.com/libgeos/geos/issues/816, https://github.com/libgeos/geos/commit/7561b50f943305b1419bd655e10e7dcad2cb9492 (cc @pramsey @dr-jts)

**Comment by dr-jts** [comment]
Yes, this is a bug in the recent code change in both JTS and GEOS.  Luckily it will be an easy fix.
